---
driver:
  name: docker
  hostname: salt-formula.ci.local
  use_sudo: false
  require_chef_omnibus: false

driver_config:
  cap_add:
  - SYS_PTRACE

# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  data_path: test/shared
  pillars:
      top.sls:
        base:
          '*':
            - joomla

      joomla.sls:
        joomla:
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: joomla
  state_top:
    base:
      '*':
        - joomla
        
suites:
  - name: joomla_high
    provisioner:
      state_top:
        base:
          '*':
            - joomla
  - name: joomla_cli
    provisioner:
      state_top:
        base:
          '*':
            - joomla.cli            
  - name: joomla_install
    provisioner:
      state_top:
        base:
          '*':
            - joomla.install
  - name: joomla_config
    provisioner:
      state_top:
        base:
          '*':
            - joomla.config