language: php

rvm:
  - 2.2.5

php:
  - '5.6'

sudo: required
services: 
  - docker
  - mysql

env:
  matrix:  
  - INSTANCE: cli-ubuntu-1404 
  - INSTANCE: cli-ubuntu-1604 
  - INSTANCE: cli-debian-7    
  - INSTANCE: cli-debian-8    
  - INSTANCE: cli-centos-6

before_script: 
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - sudo apt-get install php5-mysql
  - mysql -e 'CREATE DATABASE IF NOT EXISTS siteAdb;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS siteBdb;'

install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script: bundle exec kitchen verify ${INSTANCE}
