language: ruby

rvm:
  - 2.2.5

sudo: required
services: 
  - docker

env:
  matrix:
  - INSTANCE: install-ubuntu-1404
  - INSTANCE: install-ubuntu-1604
  - INSTANCE: install-debian-7   
  - INSTANCE: install-debian-8   
  - INSTANCE: install-centos-6   
  - INSTANCE: config-ubuntu-1404 
  - INSTANCE: config-ubuntu-1604 
  - INSTANCE: config-debian-7    
  - INSTANCE: config-debian-8    
  - INSTANCE: config-centos-6    
  - INSTANCE: cli-ubuntu-1404 
  - INSTANCE: cli-ubuntu-1604 
  - INSTANCE: cli-debian-7    
  - INSTANCE: cli-debian-8    
  - INSTANCE: cli-centos-6

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

install:
  # setup ci for test formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script: bundle exec kitchen verify ${INSTANCE}
