language: php

rvm:
  - 2.2.5

php:
  - '5.6'

sudo: required
services: 
  - docker
  - mysql
  - apache

env:
  matrix:  
  - INSTANCE: cli-ubuntu-1404 
  - INSTANCE: cli-ubuntu-1604 
  - INSTANCE: cli-debian-7    
  - INSTANCE: cli-debian-8    
  - INSTANCE: cli-centos-6

before_script: 
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - sudo apt-get install git
  - git clone https://github.com/saltstack-formulas/apache-formula.git /tmp/apache
  - git clone https://github.com/saltstack-formulas/php-formula.git /tmp/php
  - git clone https://github.com/saltstack-formulas/mysql-formula.git /tmp/mysql

install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script: bundle exec kitchen verify ${INSTANCE}
